MERGE INTO  AUTHORITIES (ID, AUTHORITY)
    VALUES (0, 'ROLE_ANONYMOUS');
MERGE INTO  AUTHORITIES (ID, AUTHORITY)
    VALUES (1, 'ROLE_ADMIN');
MERGE INTO  AUTHORITIES (ID, AUTHORITY)
    VALUES (2, 'ROLE_USER');
